# Generated by Django 2.1.5 on 2019-01-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='creado',
            field=models.DateTimeField(auto_now=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
    ]
