# Generated by Django 2.1.5 on 2019-01-23 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_auto_20190123_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='creado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='modificado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='modificado'),
        ),
    ]
