# Generated by Django 2.1.5 on 2019-01-23 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_auto_20190123_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='creado',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 23, 21, 35, 1, 503291, tzinfo=utc), verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='modificado',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 23, 21, 35, 1, 503291, tzinfo=utc), verbose_name='modificado'),
        ),
    ]
