# Generated by Django 2.1.5 on 2019-01-23 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_auto_20190123_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='creado',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='modificado',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 23, 21, 35, 40, 75544, tzinfo=utc), verbose_name='modificado'),
        ),
    ]
