# Generated by Django 2.1.5 on 2019-01-23 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_auto_20190123_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='modificado',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='modificado'),
        ),
    ]
