# Generated by Django 2.1.5 on 2019-01-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0010_auto_20190126_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuario'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buses.Horario'),
        ),
    ]
