# Generated by Django 2.1.5 on 2019-01-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0014_auto_20190126_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuario'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='buses.Horario'),
        ),
    ]
