# Generated by Django 2.1.5 on 2019-01-23 21:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('creado', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creado')),
                ('modificado', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='modificado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('creado', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creado')),
                ('modificado', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='modificado')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Rol')),
            ],
        ),
    ]
